sonar.projectKey=backend-project-46
sonar.organization=sergmit
sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.exclusions=node_modules/**,dist/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info